version: 0.0
os: linux

files:
  # buildspec에서 경로를 다 버렸으므로(discard-paths), jar파일은 바로 루트에 있습니다.
  - source:  /
    destination: /home/ec2-user/app/
    overwrite: yes

permissions:
  - object: /home/ec2-user/app/
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  # ❌ ApplicationStop 제거 (새 서버라 끌 게 없음)

  # ✅ 앱 실행만 남김
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user