version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo Build Starting...
      - chmod +x ./gradlew
      - ./gradlew clean build -x test

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - scripts/**/*
