version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17			# Java 17사용 (프로젝트 버전에 맞게 수정)

  build:
    commands:
      - echo Build Starting...
      - chmod +x ./gradlew
      - ./gradlew clean build -x test # 테스트 건너뛰고 빌드 (실습용)

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - scripts/**
  discard-paths: no