version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build Starting...
      - chmod +x ./gradlew
      - ./gradlew clean build -x test

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/libs/*.jar   # 빌드된 jar
    - appspec.yml
    - scripts/** # 스크립트 폴더 전체
  discard-paths: yes     # 중요: 파일 경로를 없애고 파일만 쏙 뽑아서 저장